from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import re
import shutil
import subprocess  # nosec B404
import tempfile
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Optional
from urllib.parse import urlparse

GITHUB_URL_RE = re.compile(r"https?://[^\s)\]\"'>]+", re.IGNORECASE)

CODE_EXTENSIONS = {
    ".py",
    ".js",
    ".ts",
    ".jsx",
    ".tsx",
    ".java",
    ".kt",
    ".kts",
    ".c",
    ".cc",
    ".cpp",
    ".cxx",
    ".h",
    ".hh",
    ".hpp",
    ".cs",
    ".go",
    ".rs",
    ".rb",
    ".php",
    ".swift",
    ".scala",
    ".sql",
    ".html",
    ".css",
    ".scss",
    ".sass",
    ".m",
    ".r",
    ".jl",
    ".sh",
    ".bash",
    ".zsh",
    ".vue",
    ".svelte",
    ".dart",
    ".lua",
    ".pl",
    ".ipynb",
}

BINARY_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".bmp",
    ".webp",
    ".ico",
    ".pdf",
    ".zip",
    ".rar",
    ".7z",
    ".tar",
    ".gz",
    ".mp3",
    ".wav",
    ".mp4",
    ".avi",
    ".mov",
    ".mkv",
    ".class",
    ".jar",
    ".exe",
    ".dll",
    ".so",
    ".o",
    ".a",
    ".pyc",
    ".pyo",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".map",
}

DEFAULT_SKIP_DIRS = {
    ".git",
    ".github",
    ".idea",
    ".vscode",
    "__pycache__",
    "node_modules",
    "vendor",
    "dist",
    "build",
    "out",
    "coverage",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".cache",
    ".gradle",
    ".mypy_cache",
    ".pytest_cache",
    ".tox",
    "venv",
    ".venv",
    "env",
    "Pods",
    "target",
    "bin",
    "obj",
    "static",
    "assets",
    "images",
    "img",
    "fonts",
}

DEFAULT_SKIP_FILES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "composer.lock",
    "poetry.lock",
    "Cargo.lock",
    "Gemfile.lock",
    "Pipfile.lock",
    "pubspec.lock",
    "favicon.ico",
}

GENERATED_MARKERS = [
    "do not edit",
    "this file was generated",
    "generated by",
    "autogenerated",
    "auto-generated",
    "automatically generated",
    "create-react-app",
    "vite",
    "webpack bootstrap",
    "@generated",
]

EXTENSION_BASE_SCORE = {
    ".py": 90,
    ".java": 88,
    ".kt": 88,
    ".kts": 70,
    ".c": 85,
    ".cc": 85,
    ".cpp": 85,
    ".cxx": 85,
    ".h": 55,
    ".hh": 55,
    ".hpp": 55,
    ".cs": 90,
    ".go": 90,
    ".rs": 92,
    ".rb": 80,
    ".php": 80,
    ".swift": 84,
    ".scala": 82,
    ".sql": 82,
    ".js": 78,
    ".ts": 82,
    ".jsx": 64,
    ".tsx": 68,
    ".vue": 70,
    ".svelte": 70,
    ".dart": 78,
    ".m": 74,
    ".r": 74,
    ".jl": 74,
    ".sh": 56,
    ".bash": 56,
    ".zsh": 56,
    ".html": 28,
    ".css": 14,
    ".scss": 18,
    ".sass": 18,
    ".lua": 72,
    ".pl": 70,
    ".ipynb": 78,
}

BONUS_PATH_PATTERNS = [
    (
        r"(^|/)(src|app|server|backend|api|core|lib|internal|pkg|cmd|domain|logic|engine)(/|$)",
        35,
    ),
    (
        r"(^|/)(controllers?|services?|handlers?|routes?|routers?|middleware|guards?|auth|security)(/|$)",
        45,
    ),
    (
        r"(^|/)(models?|entities?|dto|schemas?|database|db|repositories?|dao|migrations?)(/|$)",
        35,
    ),
    (
        r"(^|/)(parser|compiler|solver|algorithm|algorithms|graph|tree|heap|search|sort)(/|$)",
        35,
    ),
    (r"(^|/)(utils?|helpers?|shared|common)(/|$)", 18),
]

PENALTY_PATH_PATTERNS = [
    (
        r"(^|/)(test|tests|testing|__tests__|spec|specs|fixtures|mocks|mock|sample|samples|example|examples)(/|$)",
        -35,
    ),
    (
        r"(^|/)(public|docs?|documentation|assets?|images?|img|fonts?|styles?|css)(/|$)",
        -28,
    ),
    (
        r"(^|/)(vendor|third_party|third-party|external|generated|dist|build|coverage)(/|$)",
        -45,
    ),
]


@dataclass
class ExtractionConfig:
    output_root: Path
    final_dir_name: str = "trimmed_code"
    report_dir_name: str = "candidate_reports"
    summary_csv_name: str = "summary.csv"
    file_level_csv_name: str = "selected_files.csv"
    failure_log_name: str = "failures.txt"
    target_min_lines: int = 800
    target_min_words: int = 3000
    write_small_outputs: bool = True
    min_lines_per_file: int = 12
    max_lines_per_file: int = 4000
    max_file_bytes: int = 1_200_000
    max_candidate_files_per_repo: int = 60
    max_selected_files_per_repo: int = 25
    mark_line: str = "############"
    skip_dirs: set[str] = field(default_factory=lambda: set(DEFAULT_SKIP_DIRS))
    skip_files: set[str] = field(default_factory=lambda: set(DEFAULT_SKIP_FILES))

    @property
    def final_root(self) -> Path:
        return self.output_root / self.final_dir_name

    @property
    def report_root(self) -> Path:
        return self.output_root / self.report_dir_name

    @property
    def summary_csv(self) -> Path:
        return self.output_root / self.summary_csv_name

    @property
    def file_level_csv(self) -> Path:
        return self.output_root / self.file_level_csv_name

    @property
    def failure_log(self) -> Path:
        return self.output_root / self.failure_log_name


@dataclass
class RepoTarget:
    url: str
    owner: str
    repo: str
    kind: str = "repo"
    subpath: Optional[str] = None


def run(cmd: list[str], cwd: Optional[Path] = None) -> tuple[int, str]:
    proc = subprocess.run(  # nosec B603
        cmd,
        cwd=str(cwd) if cwd else None,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    return proc.returncode, proc.stdout


def normalize_url(url: str) -> str:
    return (url or "").strip().rstrip(".,;)")


def ordered_unique(items: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            out.append(item)
    return out


def is_github_url(url: str) -> bool:
    try:
        host = urlparse(url).netloc.lower()
    except Exception:  # nosec B112
        return False
    return host == "github.com" or host.endswith(".github.com") or "github.com" in host


def load_urls_from_text(path: Path) -> list[str]:
    urls: list[str] = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = normalize_url(line)
        if line and is_github_url(line):
            urls.append(line)
    return ordered_unique(urls)


def load_urls_from_json(path: Path) -> list[str]:
    data = json.loads(path.read_text(encoding="utf-8", errors="ignore"))
    if not isinstance(data, list):
        raise ValueError("JSON URL input must be a list of strings.")
    urls = [normalize_url(str(item)) for item in data]
    return [url for url in ordered_unique(urls) if is_github_url(url)]


def load_urls(path: Path) -> list[str]:
    suffix = path.suffix.lower()
    if suffix == ".json":
        urls = load_urls_from_json(path)
    else:
        urls = load_urls_from_text(path)
    if not urls:
        raise ValueError(f"No GitHub URLs found in {path}")
    return urls


def parse_github_target(url: str) -> Optional[RepoTarget]:
    match = re.match(r"https?://github\.com/([^/]+)/([^/]+)(?:/(.*))?$", url.strip())
    if not match:
        return None
    owner = match.group(1)
    repo = match.group(2).replace(".git", "")
    tail = (match.group(3) or "").strip("/")
    target = RepoTarget(url=url, owner=owner, repo=repo)
    if tail.startswith("tree/"):
        parts = tail.split("/", 2)
        target.kind = "tree"
        target.subpath = parts[2] if len(parts) > 2 else None
    elif tail.startswith("blob/"):
        parts = tail.split("/", 2)
        target.kind = "blob"
        target.subpath = parts[2] if len(parts) > 2 else None
    return target


def safe_slug(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", text).strip("._") or "item"


def output_stem(target: RepoTarget) -> str:
    base = f"{target.owner}__{target.repo}"
    digest = hashlib.sha256(target.url.encode("utf-8")).hexdigest()[:10]
    return safe_slug(f"{base}__{digest}")


def git_clone_repo(target: RepoTarget, dest_dir: Path) -> tuple[bool, str]:
    dest_dir.parent.mkdir(parents=True, exist_ok=True)
    if dest_dir.exists():
        shutil.rmtree(dest_dir, ignore_errors=True)

    primary = [
        "git",
        "clone",
        "--depth",
        "1",
        "--single-branch",
        f"https://github.com/{target.owner}/{target.repo}.git",
        str(dest_dir),
    ]
    rc, out = run(primary)
    if rc == 0:
        return True, out

    if dest_dir.exists():
        shutil.rmtree(dest_dir, ignore_errors=True)

    fallback = [
        "git",
        "clone",
        "--depth",
        "1",
        f"https://github.com/{target.owner}/{target.repo}.git",
        str(dest_dir),
    ]
    rc2, out2 = run(fallback)
    return rc2 == 0, out + "\n\nRETRY:\n" + out2


def is_probably_binary(path: Path) -> bool:
    try:
        with path.open("rb") as handle:
            chunk = handle.read(8192)
    except Exception:  # nosec B112
        return True
    if b"\x00" in chunk:
        return True
    if not chunk:
        return False
    bad = sum(1 for byte in chunk if byte < 9 or (13 < byte < 32))
    return bad / max(1, len(chunk)) > 0.20


def read_text_file(path: Path) -> str:
    for encoding in ("utf-8", "utf-8-sig", "latin-1", "cp1252"):
        try:
            return path.read_text(encoding=encoding, errors="ignore")
        except Exception:  # nosec B112
            continue
    return ""


def read_notebook_code(path: Path) -> str:
    try:
        data = json.loads(read_text_file(path))
    except Exception:  # nosec B112
        return ""
    cells = data.get("cells", [])
    kept: list[str] = []
    for cell in cells:
        if cell.get("cell_type") != "code":
            continue
        source = cell.get("source", [])
        if isinstance(source, list):
            source = "".join(source)
        source = (source or "").rstrip()
        if source:
            kept.append(source)
    if not kept:
        return ""
    return "\n\n# %%\n\n".join(kept) + "\n"


def extract_text(path: Path) -> str:
    if path.suffix.lower() == ".ipynb":
        return read_notebook_code(path)
    return read_text_file(path)


def count_words(text: str) -> int:
    return len(re.findall(r"[A-Za-z0-9_]+", text))


def count_lines(text: str) -> int:
    return len(text.splitlines())


def path_penalty_or_bonus(rel_path: str) -> int:
    normalized = rel_path.lower().replace("\\", "/")
    score = 0
    for pattern, value in BONUS_PATH_PATTERNS:
        if re.search(pattern, normalized):
            score += value
    for pattern, value in PENALTY_PATH_PATTERNS:
        if re.search(pattern, normalized):
            score += value
    if (
        normalized.endswith(".min.js")
        or normalized.endswith(".min.css")
        or normalized.endswith(".bundle.js")
    ):
        score -= 100
    return score


def looks_generated(text: str) -> bool:
    head = text[:6000].lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def looks_minified(text: str, rel_path: str) -> bool:
    rel = rel_path.lower()
    if (
        rel.endswith(".min.js")
        or rel.endswith(".min.css")
        or rel.endswith(".bundle.js")
    ):
        return True
    lines = text.splitlines()
    if len(lines) < 8:
        return False
    long_lines = sum(1 for line in lines if len(line) > 450)
    avg_len = sum(len(line) for line in lines) / max(1, len(lines))
    if long_lines / len(lines) > 0.35 and avg_len > 160:
        return True
    if "\n" not in text[:5000] and len(text) > 5000:
        return True
    return False


def import_heavy_ratio(text: str) -> float:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if not lines:
        return 1.0
    head = lines[: min(120, len(lines))]
    pattern = re.compile(
        r"^(import\s|from\s.+\simport\s|#include\s|using\s+namespace|using\s+[A-Za-z0-9_.:]+\s*=|require\(|package\s+[A-Za-z0-9_.]+;)"
    )
    hits = sum(1 for line in head if pattern.search(line))
    return hits / max(1, len(head))


def comment_ratio(text: str) -> float:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if not lines:
        return 1.0
    comment_like = 0
    for line in lines:
        if line.startswith(("#", "//", "/*", "*", "--")):
            comment_like += 1
    return comment_like / len(lines)


def repeated_line_ratio(text: str) -> float:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    if not lines:
        return 1.0
    counts = Counter(lines)
    repeated = sum(value for value in counts.values() if value > 1)
    return repeated / len(lines)


def syntax_score(text: str, ext: str) -> int:
    lowered = text.lower()
    score = 0
    score += 4 * len(
        re.findall(
            r"\b(if|else|elif|switch|case|for|foreach|while|do|try|catch|except|finally|throw|return|yield|break|continue)\b",
            lowered,
        )
    )
    score += 4 * len(
        re.findall(
            r"\b(def|function|func|class|interface|enum|struct|trait|impl|namespace|template|lambda|async|await)\b",
            lowered,
        )
    )
    score += 3 * len(
        re.findall(
            r"\b(public|private|protected|extends|implements|override|virtual|static|const|final|new|super|self|this)\b",
            lowered,
        )
    )
    score += 4 * len(
        re.findall(
            r"\b(select|insert|update|delete|join|where|group by|order by|create table|alter table|schema|transaction|commit|rollback)\b",
            lowered,
        )
    )
    score += 3 * len(
        re.findall(
            r"\b(auth|token|jwt|bcrypt|hash|encrypt|decrypt|serialize|deserialize|validate|parser?|compile|solver|algorithm|graph|tree|heap|queue|stack)\b",
            lowered,
        )
    )
    score += 3 * len(
        re.findall(
            r"\b(request|response|router|route|endpoint|server|client|http|https|api|fetch|axios|requests|socket)\b",
            lowered,
        )
    )

    if ext == ".py":
        score += 8 * len(re.findall(r"(?m)^\s*def\s+[A-Za-z_][A-Za-z0-9_]*\s*\(", text))
        score += 8 * len(
            re.findall(r"(?m)^\s*class\s+[A-Za-z_][A-Za-z0-9_]*\s*[:(]", text)
        )
    elif ext in {".js", ".ts", ".jsx", ".tsx", ".vue", ".svelte"}:
        score += 7 * len(
            re.findall(r"\bfunction\s+[A-Za-z_$][A-Za-z0-9_$]*\s*\(", text)
        )
        score += 6 * len(
            re.findall(r"\b[A-Za-z_$][A-Za-z0-9_$]*\s*=\s*\([^)]*\)\s*=>", text)
        )
        score += 6 * len(re.findall(r"\bclass\s+[A-Za-z_$][A-Za-z0-9_$]*", text))
    elif ext in {
        ".java",
        ".kt",
        ".kts",
        ".c",
        ".cc",
        ".cpp",
        ".cxx",
        ".h",
        ".hh",
        ".hpp",
        ".cs",
        ".go",
        ".rs",
        ".swift",
        ".scala",
        ".php",
        ".rb",
        ".dart",
        ".m",
    }:
        score += 7 * len(
            re.findall(r"\b(class|interface|struct|enum|impl|trait|namespace)\b", text)
        )
        score += 5 * len(
            re.findall(
                r"\b[A-Za-z_][A-Za-z0-9_<>:\[\]]*\s+[A-Za-z_][A-Za-z0-9_]*\s*\([^;\n]*\)\s*\{",
                text,
            )
        )
    elif ext == ".sql":
        score += 12 * len(
            re.findall(
                r"\b(select|insert|update|delete|create|alter|drop|join|where|group by|order by)\b",
                lowered,
            )
        )
    elif ext in {".sh", ".bash", ".zsh"}:
        score += 6 * len(
            re.findall(r"\b(if|then|fi|for|while|case|function)\b", lowered)
        )

    nonempty = [line for line in text.splitlines() if line.strip()]
    score += min(len(nonempty), 400) // 6

    html_tags = len(re.findall(r"<[A-Za-z][^>]*>", text))
    css_props = len(
        re.findall(
            r"\b(color|margin|padding|font|display|position|background|border)\s*:",
            lowered,
        )
    )
    if ext in {".html", ".css", ".scss", ".sass"}:
        score -= int((html_tags + css_props) * 0.6)
    elif html_tags > 250 and ext in {".jsx", ".tsx", ".vue", ".svelte"}:
        score -= int(html_tags * 0.12)

    score -= int(comment_ratio(text) * 40)
    score -= int(repeated_line_ratio(text) * 70)

    if import_heavy_ratio(text) > 0.82:
        score -= 35
    if looks_generated(text):
        score -= 60
    return score


def keep_file(path: Path, config: ExtractionConfig) -> bool:
    name = path.name
    lower_name = name.lower()
    ext = path.suffix.lower()
    skip_files_lower = {item.lower() for item in config.skip_files}

    if name in config.skip_files or lower_name in skip_files_lower:
        return False
    if ext in BINARY_EXTENSIONS:
        return False
    if ext not in CODE_EXTENSIONS:
        return False
    try:
        if path.stat().st_size > config.max_file_bytes:
            return False
    except Exception:  # nosec B112
        return False
    if is_probably_binary(path):
        return False
    return True


def candidate_score(
    rel_path: str, text: str, config: ExtractionConfig
) -> tuple[int, dict]:
    ext = Path(rel_path).suffix.lower()
    if ext not in CODE_EXTENSIONS:
        return 0, {"reason": "unsupported_extension"}
    if not text.strip():
        return 0, {"reason": "empty"}

    lines = count_lines(text)
    words = count_words(text)
    if lines < config.min_lines_per_file:
        return 0, {"reason": "too_short", "lines": lines, "words": words}
    if lines > config.max_lines_per_file:
        return 0, {"reason": "too_long", "lines": lines, "words": words}
    if looks_minified(text, rel_path):
        return 0, {"reason": "minified", "lines": lines, "words": words}

    base = EXTENSION_BASE_SCORE.get(ext, 40)
    score = base + path_penalty_or_bonus(rel_path) + syntax_score(text, ext)
    if ext in {".html", ".css", ".scss", ".sass"} and score < 60:
        score -= 40

    meta = {"lines": lines, "words": words, "ext": ext, "score_before_floor": score}
    return max(0, score), meta


def collect_candidates(
    repo_root: Path, base_path: Path, config: ExtractionConfig
) -> list[dict]:
    candidates: list[dict] = []
    seen_hashes: set[str] = set()

    for root, dirs, files in os.walk(base_path):
        dirs[:] = [directory for directory in dirs if directory not in config.skip_dirs]
        for filename in files:
            path = Path(root) / filename
            if not keep_file(path, config):
                continue
            rel = str(path.relative_to(repo_root)).replace("\\", "/")
            text = extract_text(path)
            if not text.strip():
                continue
            digest = hashlib.sha256(
                text[:250000].encode("utf-8", errors="ignore")
            ).hexdigest()
            if digest in seen_hashes:
                continue
            seen_hashes.add(digest)
            score, meta = candidate_score(rel, text, config)
            if score <= 0:
                continue
            candidates.append(
                {
                    "file_rel": rel,
                    "text": text,
                    "score": score,
                    "lines": meta.get("lines", 0),
                    "words": meta.get("words", 0),
                    "ext": meta.get("ext", ""),
                }
            )

    candidates.sort(
        key=lambda item: (item["score"], item["lines"], item["words"]), reverse=True
    )
    return candidates[: config.max_candidate_files_per_repo]


def choose_files(
    candidates: list[dict], config: ExtractionConfig
) -> tuple[list[dict], int, int, bool]:
    selected: list[dict] = []
    total_lines = 0
    total_words = 0

    for candidate in candidates:
        if len(selected) >= config.max_selected_files_per_repo:
            break
        selected.append(candidate)
        total_lines += candidate["lines"]
        total_words += candidate["words"]
        if (
            total_lines >= config.target_min_lines
            or total_words >= config.target_min_words
        ):
            break

    reached = (
        total_lines >= config.target_min_lines or total_words >= config.target_min_words
    )
    if not reached and not config.write_small_outputs:
        return [], total_lines, total_words, reached
    return selected, total_lines, total_words, reached


def write_final_txt(path: Path, selected: list[dict], config: ExtractionConfig) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", errors="ignore") as handle:
        for index, candidate in enumerate(selected):
            if index > 0:
                handle.write("\n" + config.mark_line + "\n\n")
            handle.write(candidate["file_rel"].strip() + "\n")
            text = candidate["text"]
            handle.write(text if text.endswith("\n") else text + "\n")


def write_candidate_report(
    path: Path,
    url: str,
    candidates: list[dict],
    selected: list[dict],
    total_lines: int,
    total_words: int,
    reached: bool,
    config: ExtractionConfig,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    selected_paths = {candidate["file_rel"] for candidate in selected}
    with path.open("w", encoding="utf-8", errors="ignore") as handle:
        handle.write(f"URL: {url}\n")
        handle.write(f"Candidates found: {len(candidates)}\n")
        handle.write(f"Selected files: {len(selected)}\n")
        handle.write(f"Selected total lines: {total_lines}\n")
        handle.write(f"Selected total words: {total_words}\n")
        handle.write(
            f"Threshold reached ({config.target_min_lines} lines OR {config.target_min_words} words): {reached}\n\n"
        )
        handle.write("RANK | SELECTED | SCORE | LINES | WORDS | EXT | FILE\n")
        handle.write("-" * 120 + "\n")
        for index, candidate in enumerate(candidates, 1):
            mark = "YES" if candidate["file_rel"] in selected_paths else "NO"
            handle.write(
                f"{index:>4} | {mark:^8} | {candidate['score']:>5} | {candidate['lines']:>5} | "
                f"{candidate['words']:>5} | {candidate['ext']:<6} | {candidate['file_rel']}\n"
            )


def process_one_repo(url: str, tmp_parent: Path, config: ExtractionConfig) -> dict:
    target = parse_github_target(url)
    if not target:
        return {
            "status": "bad_url",
            "url": url,
            "message": "Could not parse GitHub URL.",
        }

    stem = output_stem(target)
    repo_dir = tmp_parent / stem
    ok, clone_log = git_clone_repo(target, repo_dir)
    if not ok:
        return {
            "status": "clone_failed",
            "url": url,
            "owner": target.owner,
            "repo": target.repo,
            "message": clone_log,
            "stem": stem,
        }

    base_path = repo_dir
    if target.kind in {"tree", "blob"} and target.subpath:
        maybe = repo_dir / target.subpath
        if maybe.exists():
            base_path = maybe if maybe.is_dir() else maybe.parent

    candidates = collect_candidates(repo_dir, base_path, config)
    if not candidates:
        return {
            "status": "no_candidates",
            "url": url,
            "owner": target.owner,
            "repo": target.repo,
            "stem": stem,
            "message": "No qualifying code files found after filtering and scoring.",
        }

    selected, total_lines, total_words, reached = choose_files(candidates, config)
    if not selected:
        return {
            "status": "below_threshold",
            "url": url,
            "owner": target.owner,
            "repo": target.repo,
            "stem": stem,
            "message": "Repo had candidates, but small-output writing is disabled.",
            "candidate_count": len(candidates),
        }

    out_txt = config.final_root / f"{stem}.txt"
    report_txt = config.report_root / f"{stem}.txt"
    write_final_txt(out_txt, selected, config)
    write_candidate_report(
        report_txt, url, candidates, selected, total_lines, total_words, reached, config
    )

    return {
        "status": "written" if reached else "written_small",
        "url": url,
        "owner": target.owner,
        "repo": target.repo,
        "stem": stem,
        "candidate_count": len(candidates),
        "selected_count": len(selected),
        "selected_lines": total_lines,
        "selected_words": total_words,
        "threshold_reached": reached,
        "output_path": str(out_txt),
        "report_path": str(report_txt),
        "selected": selected,
    }


def write_failure_log(failures: list[dict], config: ExtractionConfig) -> None:
    config.failure_log.parent.mkdir(parents=True, exist_ok=True)
    with config.failure_log.open("w", encoding="utf-8", errors="ignore") as handle:
        if not failures:
            handle.write("(none)\n")
            return
        for item in failures:
            handle.write("=" * 100 + "\n")
            handle.write(f"URL: {item.get('url', '')}\n")
            handle.write(f"STATUS: {item.get('status', '')}\n")
            handle.write(f"MESSAGE:\n{item.get('message', '')}\n\n")


def write_summary(rows: list[dict], config: ExtractionConfig) -> None:
    config.output_root.mkdir(parents=True, exist_ok=True)
    with config.summary_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "url",
                "owner",
                "repo",
                "status",
                "candidate_count",
                "selected_count",
                "selected_lines",
                "selected_words",
                "threshold_reached",
                "output_path",
                "report_path",
            ],
        )
        writer.writeheader()
        for row in rows:
            writer.writerow(
                {
                    "url": row.get("url", ""),
                    "owner": row.get("owner", ""),
                    "repo": row.get("repo", ""),
                    "status": row.get("status", ""),
                    "candidate_count": row.get("candidate_count", 0),
                    "selected_count": row.get("selected_count", 0),
                    "selected_lines": row.get("selected_lines", 0),
                    "selected_words": row.get("selected_words", 0),
                    "threshold_reached": row.get("threshold_reached", False),
                    "output_path": row.get("output_path", ""),
                    "report_path": row.get("report_path", ""),
                }
            )

    with config.file_level_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "url",
                "owner",
                "repo",
                "status",
                "selected_rank",
                "file_rel",
                "ext",
                "score",
                "lines",
                "words",
            ],
        )
        writer.writeheader()
        for row in rows:
            for index, item in enumerate(row.get("selected", []), 1):
                writer.writerow(
                    {
                        "url": row.get("url", ""),
                        "owner": row.get("owner", ""),
                        "repo": row.get("repo", ""),
                        "status": row.get("status", ""),
                        "selected_rank": index,
                        "file_rel": item.get("file_rel", ""),
                        "ext": item.get("ext", ""),
                        "score": item.get("score", 0),
                        "lines": item.get("lines", 0),
                        "words": item.get("words", 0),
                    }
                )


def process_repositories(urls: list[str], config: ExtractionConfig) -> list[dict]:
    config.final_root.mkdir(parents=True, exist_ok=True)
    config.report_root.mkdir(parents=True, exist_ok=True)
    config.output_root.mkdir(parents=True, exist_ok=True)

    rows: list[dict] = []
    failures: list[dict] = []

    with tempfile.TemporaryDirectory() as tmp:
        tmp_parent = Path(tmp)
        for url in urls:
            result = process_one_repo(url, tmp_parent, config)
            rows.append(result)
            if result.get("status") in {
                "clone_failed",
                "bad_url",
                "no_candidates",
                "below_threshold",
            }:
                failures.append(result)

    write_summary(rows, config)
    write_failure_log(failures, config)
    return rows


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Clone GitHub repositories and extract high-signal code samples into plain-text bundles."
    )
    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Path to a .txt or .json file containing GitHub URLs.",
    )
    parser.add_argument(
        "--output-root",
        required=True,
        type=Path,
        help="Directory for extracted outputs and reports.",
    )
    parser.add_argument("--target-min-lines", type=int, default=800)
    parser.add_argument("--target-min-words", type=int, default=3000)
    parser.add_argument("--write-small-outputs", action="store_true", default=False)
    parser.add_argument("--max-candidate-files-per-repo", type=int, default=60)
    parser.add_argument("--max-selected-files-per-repo", type=int, default=25)
    return parser


def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()

    urls = load_urls(args.input)
    config = ExtractionConfig(
        output_root=args.output_root,
        target_min_lines=args.target_min_lines,
        target_min_words=args.target_min_words,
        write_small_outputs=args.write_small_outputs,
        max_candidate_files_per_repo=args.max_candidate_files_per_repo,
        max_selected_files_per_repo=args.max_selected_files_per_repo,
    )

    rows = process_repositories(urls, config)
    status_counts = Counter(row.get("status", "unknown") for row in rows)
    for status, count in sorted(status_counts.items()):
        print(f"{status}: {count}")
    print(f"summary_csv: {config.summary_csv}")
    print(f"file_level_csv: {config.file_level_csv}")
    print(f"failure_log: {config.failure_log}")
    print(f"final_root: {config.final_root}")
    print(f"report_root: {config.report_root}")


if __name__ == "__main__":
    main()
